server:
  port: 8080

spring:
  application:
    name: kafka-streams-example
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer